apiVersion: apps/v1
kind: Deployment
metadata:
  name: computers-deployment
  labels:
    app: computers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: computers
  template:
    metadata:
      labels:
        app: computers
    spec:
      containers:
      - name: computers
        image: 992382830933.dkr.ecr.us-east-1.amazonaws.com/shopping-site-computers:16e6a6f69b604bcea2e948e8290b427db88f2d20
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: computers-service
  labels:
    app: computers
spec:
  type: ClusterIP
  selector:
    app: computers
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
